export const ROUTES_CONST = {
    INDEX: '',
    CASINO: '/games',
    SPORTS: '/sports',
    GIVEAWAY: '/giveaway',
    AFFILIATE: '/affiliate',
    AFFILIATE_DASHBOARD: '/affiliate-dashboard',
    VIP_CLUB: '/vip-club',
    PROMOTIONS: "/promotions",
    AFFILIATE: "/affiliate",
    FAIRNESS: "/fairness",
    FORUM: "/forum",
    BLOG: "/blog",
    NEWS: "/news",
    PARTNERS: "/partners",
    GLOBAL_SETTINGS: "/global-settings",
}